package survival

// ------------------
// SMALL
// ------------------

land: Land = {
	ring    = 0,
	segment = 0,
	slices  = []LandRow {
		{ring = 2, segment = 0, width = 30},
		{ring = 1, segment = 0, width = 10},
		{ring = 1, segment = 11, width = 10},
		{ring = 1, segment = 22, width = 10},
	},
}

// land: Land = {
// 	start_ring    = 0,
// 	start_segment = 20,
// 	rows          = []LandRow {
// 		{start = 0, width = 2},
// 		// {start = 0, width = 16},
// 		// {start = 0, width = 40},
// 	},
// }

// ------------------
// MEDIUM
// ------------------

// land: Land = {
// 	start_ring    = 0,
// 	// Need to make sure the start segment is not inside of a tile
// 	// start_segment = globe_land_segments - 2,
// 	start_segment = 20,
// 	rows          = []LandRow {
// 		{start = 5, width = 20},
// 		{start = 2, width = 31},
// 		{start = 0, width = 36},
// 		{start = 0, width = 37},
// 		{start = 0, width = 36},
// 		{start = 0, width = 34},
// 		{start = 1, width = 32},
// 		{start = 1, width = 30},
// 		{start = 1, width = 30},
// 		{start = 1, width = 30},
// 		{start = 2, width = 30},
// 		{start = 2, width = 15},
// 		{start = 2, width = 15},
// 		{start = 2, width = 15},
// 		{start = 3, width = 15},
// 		{start = 4, width = 15},
// 		{start = 6, width = 15},
// 		{start = 6, width = 15},
// 		{start = 7, width = 15},
// 		{start = 9, width = 15},
// 		{start = 10, width = 10},
// 	},
// }

// ------------------
// LARGE
// ------------------

// land: Land = {
// 	start_ring    = 0,
// 	// Need to make sure the start segment is not inside of a tile
// 	// start_segment = globe_land_segments - 2,
// 	start_segment = 20,
// 	rows          = []LandRow {
// 		{start = 10, width = 10},
// 		{start = 8, width = 14},
// 		{start = 6, width = 16},
// 		{start = 5, width = 20},
// 		{start = 3, width = 24},
// 		{start = 3, width = 25},
// 		{start = 1, width = 30},
// 		{start = 1, width = 31},
// 		{start = 0, width = 32},
// 		{start = 0, width = 34},
// 		{start = 0, width = 33},
// 		{start = 0, width = 32},
// 		{start = 1, width = 32},
// 		{start = 1, width = 30},
// 		{start = 1, width = 31},
// 		{start = 1, width = 33},
// 		{start = 2, width = 34},
// 		{start = 1, width = 35},
// 		{start = 0, width = 35},
// 		{start = 0, width = 36},
// 		{start = 0, width = 35},
// 		{start = 0, width = 36},
// 		{start = 0, width = 34},
// 		{start = 1, width = 32},
// 		{start = 1, width = 30},
// 		{start = 1, width = 30},
// 		{start = 1, width = 30},
// 		{start = 2, width = 30},
// 		{start = 1, width = 33},
// 		{start = 0, width = 37},
// 		{start = 0, width = 36},
// 		{start = 0, width = 34},
// 		{start = 1, width = 32},
// 		{start = 1, width = 30},
// 		{start = 1, width = 30},
// 		{start = 1, width = 31},
// 		{start = 2, width = 32},
// 		{start = 0, width = 32},
// 		{start = 0, width = 34},
// 		{start = 0, width = 33},
// 		{start = 0, width = 32},
// 		{start = 1, width = 32},
// 		{start = 1, width = 30},
// 		{start = 1, width = 31},
// 		{start = 1, width = 33},
// 		{start = 2, width = 34},
// 		{start = 1, width = 35},
// 		{start = 0, width = 35},
// 		{start = 0, width = 36},
// 		{start = 0, width = 35},
// 		{start = 0, width = 36},
// 		{start = 0, width = 34},
// 		{start = 1, width = 32},
// 		{start = 1, width = 30},
// 		{start = 1, width = 30},
// 		{start = 1, width = 30},
// 		{start = 2, width = 30},
// 		{start = 1, width = 33},
// 		{start = 0, width = 37},
// 		{start = 0, width = 36},
// 		{start = 0, width = 34},
// 		{start = 1, width = 32},
// 		{start = 1, width = 30},
// 		{start = 1, width = 30},
// 		{start = 1, width = 31},
// 		{start = 2, width = 32},
// 		{start = 1, width = 33},
// 		///
// 		{start = 2, width = 31},
// 		// {start = 5, width = 20},
// 		{start = 2, width = 31},
// 		{start = 0, width = 36},
// 		{start = 0, width = 37},
// 		{start = 0, width = 36},
// 		{start = 0, width = 34},
// 		{start = 1, width = 32},
// 		{start = 1, width = 30},
// 		{start = 1, width = 30},
// 		{start = 1, width = 30},
// 		{start = 2, width = 30},
// 		{start = 2, width = 28},
// 		{start = 2, width = 26},
// 		{start = 2, width = 24},
// 		{start = 3, width = 22},
// 		{start = 4, width = 20},
// 		{start = 6, width = 19},
// 		{start = 6, width = 17},
// 		{start = 7, width = 15},
// 		{start = 9, width = 13},
// 		{start = 10, width = 10},
// 	},
// }

// ------------------
// RECTANGLE
// ------------------

// land: Land = {
// 	start_ring    = 0,
// 	// Need to make sure the start segment is not inside of a tile
// 	// start_segment = globe_land_segments - 2,
// 	start_segment = 50,
// 	rows          = []LandRow {
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 		{start = 0, width = 40},
// 	},
// }
